---
sidebar: sidebar 
permalink: rp-reference-roles.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: 'La protección contra ransomware de BlueXP  usa el control de acceso basado en roles (RBAC) para gobernar el acceso que tiene cada usuario a funciones y acciones específicas. El servicio utiliza roles específicos de la protección contra ransomware de BlueXP  (RPS).' 
---
= Acceso a funciones basado en roles de protección frente al ransomware de BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La protección frente al ransomware de BlueXP  emplea roles para gobernar el acceso que cada usuario tiene a funciones y acciones específicas.

El servicio utiliza los siguientes roles específicos de la protección contra ransomware de BlueXP .

* *Ransomware protection admin*: Administrar acciones en las pestañas Proteger, Alertas, Recuperar, Configuración e Informes.
* *Visor de protección contra ransomware*: Ver datos de carga de trabajo, ver datos de alerta, descargar datos de recuperación e informes de descarga.


La plataforma BlueXP  para todos los servicios BlueXP  utiliza los siguientes tipos de roles:

* * Los roles de la plataforma * le permiten administrar usuarios, asignarlos a recursos y darles roles junto con otras acciones de toda la plataforma.
* *Los roles de servicios de datos* se limitan solo a un servicio de datos específico. Puede tener varios roles de servicios de datos en función del trabajo. La protección contra ransomware de BlueXP  es uno de los servicios de datos de BlueXP .


Otros roles de la plataforma BlueXP  se tratan como espectadores en la protección contra ransomware de BlueXP . Por ejemplo, la función *Visor de protección contra ransomware* le permite ver los planes de protección, pero no le permite realizar ninguna acción en la protección contra ransomware de BlueXP.

Para obtener más información sobre todos los roles de la plataforma BlueXP , consulte https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["La documentación de configuración y administración de BlueXP "^].

La siguiente tabla indica las acciones que puede realizar cada rol de protección contra ransomware de BlueXP .

[cols="40,20a,20a"]
|===
| Característica y acción | Administrador de protección frente a ransomware | Visor de protección contra ransomware 


| Ver panel y todas las pestañas  a| 
Sí
 a| 
Sí



| En el panel de control, actualice el estado de la recomendación  a| 
Sí
 a| 
No



| Inicie una prueba gratuita  a| 
Sí
 a| 
No



| Inicie la detección de las cargas de trabajo  a| 
Sí
 a| 
No



| Inicie la nueva detección de cargas de trabajo  a| 
Sí
 a| 
No



3+| *En la pestaña Proteger*: 


| Agregar, modificar o eliminar planes de protección  a| 
Sí
 a| 
No



| Proteja las cargas de trabajo  a| 
Sí
 a| 
No



| Identificar la exposición a datos confidenciales  a| 
Sí
 a| 
No



| Lista de planes de protección y detalles  a| 
Sí
 a| 
Sí



| Enumerar los grupos de protección  a| 
Sí
 a| 
Sí



| Ver los detalles del grupo de protección  a| 
Sí
 a| 
Sí



| Cree, edite o elimine el grupo de protección  a| 
Sí
 a| 
No



| Descargar datos  a| 
Sí
 a| 
Sí



3+| *En la pestaña Alertas*: 


| Ver alertas y detalles de alertas  a| 
Sí
 a| 
Sí



| Editar el estado del incidente  a| 
Sí
 a| 
No



| Marcar alerta para recuperación  a| 
Sí
 a| 
No



| Ver detalles del incidente  a| 
Sí
 a| 
Sí



| Descarte o resuelva los incisos  a| 
Sí
 a| 
No



| Usuario de bloque  a| 
Sí
 a| 
No



| Obtener una lista completa de archivos afectados  a| 
Sí
 a| 
No



| Descargar datos de alertas  a| 
Sí
 a| 
Sí



3+| *En la pestaña Recuperar*: 


| Descargar archivos afectados  a| 
Sí
 a| 
No



| Restaure la carga de trabajo  a| 
Sí
 a| 
No



| Descargar datos de recuperación  a| 
Sí
 a| 
Sí



| Descargar informes  a| 
Sí
 a| 
Sí



3+| *En la pestaña Configuración*: 


| Agregar o modificar destinos de copia de seguridad  a| 
Sí
 a| 
No



| Mostrar destinos de backup  a| 
Sí
 a| 
Sí



| Ver destinos de SIEM conectados  a| 
Sí
 a| 
Sí



| Agregue o modifique destinos de SIEM  a| 
Sí
 a| 
No



| Conectar destinos de seguridad de carga de trabajo  a| 
Sí
 a| 
No



| Ver el estado de conexión de seguridad de la carga de trabajo  a| 
Sí
 a| 
Sí



| Desconecte los destinos de seguridad de carga de trabajo  a| 
Sí
 a| 
No



| Configurar detalle de preparación  a| 
Sí
 a| 
No



| Inicie el ejercicio de preparación  a| 
Sí
 a| 
No



| Restablezca el detalle de preparación  a| 
Sí
 a| 
No



| Editar detalle de preparación  a| 
Sí
 a| 
No



| Revisión del estado de detalle de preparación  a| 
Sí
 a| 
Sí



| Actualice la configuración de detección  a| 
Sí
 a| 
No



| Ver la configuración de detección  a| 
Sí
 a| 
Sí



3+| *En la pestaña Informes*: 


| Descargar informes  a| 
Sí
 a| 
Sí

|===