---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: Empieza a usar la protección contra el ransomware de BlueXP verificando la compatibilidad de tu entorno, el acceso a la red, el inicio de sesión y el navegador web. 
---
= Requisitos previos de protección contra ransomware de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Comience a usar la protección frente al ransomware de BlueXP verificando la preparación de su entorno operativo, inicio de sesión, acceso a red y navegador web.

Para utilizar la protección contra ransomware de BlueXP, necesitarás estos requisitos previos:

* Para la versión de vista previa, necesitará una cuenta en NetApp StorageGRID o AWS S3 para los destinos de copia de seguridad y el conjunto de permisos de AWS.
+
Consulte la https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Lista de permisos de AWS"^] para obtener más detalles.

* ONTAP 9.11.1 y versiones posteriores
+
** Permisos de la ONTAP del administrador de clústeres
** Una licencia de la protección autónoma frente a ransomware de NetApp, que usa la protección frente a ransomware de BlueXP, en la instancia de ONTAP, según la versión de ONTAP que esté utilizando. Consulte https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Información general sobre la protección de ransomware autónoma"^].


* En BlueXP:
+
** Hay que configurar un conector BlueXP por región en la nube o en una región on-premises en NetApp BlueXP. Todos los entornos de trabajo y origen deben estar en la misma cuenta de BlueXP. Consulte https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Documentación de BlueXP para configurar el Connector"^].
+

NOTE: Si tienes varios BlueXP Connectors, el servicio analizará los datos en todos los conectores más allá de los que se muestren actualmente en la interfaz de usuario de BlueXP.

** El servicio de backup y recuperación de BlueXP con backup habilitado en el entorno de trabajo
** Se debe configurar el entorno de trabajo de BlueXP con almacenamiento en las instalaciones NAS de NetApp.
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos estándar de BlueXP"^]



