---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: Empieza a usar la protección contra el ransomware de BlueXP verificando la compatibilidad de tu entorno, el acceso a la red, el inicio de sesión y el navegador web. 
---
= Requisitos previos de protección contra ransomware de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Comience a usar la protección frente al ransomware de BlueXP verificando la preparación de su entorno operativo, inicio de sesión, acceso a red y navegador web.

Para utilizar la BlueXP ransomware protection, necesitará los requisitos previos.



== En BlueXP 

* Cuenta de usuario de BlueXP  con Privileges de administración de la organización para detectar recursos.
* Una organización BlueXP con al menos un conector BlueXP activo que se conecta a clústeres ONTAP locales o a Cloud Volumes ONTAP en AWS o en Azure.
* El conector BlueXP  debe tener el `cloudmanager-ransomware-protection` contenedor en un estado activo.
* Al menos un entorno de trabajo BlueXP con un clúster ONTAP local de NetApp o Cloud Volumes ONTAP en AWS o Azure. La BlueXP ransomware protection es compatible con los protocolos NAS (NFS y SMB) y SAN (iSCSI, FC y NVMe).
+
** Se admiten clústeres ONTAP o Cloud Volumes ONTAP con sistema operativo ONTAP versión 9.11.1 o superior.
+

NOTE: Las cargas de trabajo SAN solo son compatibles con ONTAP 9.17.1 y versiones posteriores.

** Si sus clústeres ONTAP locales o Cloud Volumes ONTAP en AWS o en la nube de Azure aún no están incorporados en BlueXP, necesita un conector BlueXP .
+
Consulte https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["Aprenda a configurar un conector BlueXP "] y. https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos estándar de BlueXP"^]

+

NOTE: Si tiene varios conectores BlueXP  en una única organización de BlueXP , el servicio de protección contra ransomware de BlueXP  analizará los recursos de ONTAP en todos los conectores más allá de los seleccionados actualmente en la interfaz de usuario de BlueXP .







== En ONTAP 9.11.1 y posterior

* Se habilita una licencia ONTAP One en la instancia local de ONTAP.
* Una licencia de la protección autónoma frente a ransomware de NetApp, utilizada por la protección frente a ransomware de BlueXP, habilitada en la instancia de ONTAP en las instalaciones, según la versión de ONTAP que esté utilizando. Consulte https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Información general sobre la protección de ransomware autónoma"^].
+

NOTE: La versión general de la protección contra ransomware de BlueXP, a diferencia de la versión Preview, incluye una licencia de la tecnología autónoma de protección frente a ransomware de NetApp. Consulte https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Información general sobre la protección de ransomware autónoma"^] para obtener más detalles.

+
Para obtener más información sobre las licencias, consulte link:concept-ransomware-protection.html["Obtén más información sobre la protección frente al ransomware de BlueXP"].

* Para aplicar configuraciones de protección (como habilitar la protección autónoma frente a ransomware, entre otras), la protección frente a ransomware de BlueXP  necesita permisos de administrador en el clúster de ONTAP. El clúster de ONTAP se debe haber incorporado solo con las credenciales de usuario administrador del clúster de ONTAP.
* Si el clúster de ONTAP ya está incorporado en BlueXP  con credenciales de usuario no administradores, se deben actualizar los permisos de usuario no administrador con los permisos necesarios iniciando sesión en el clúster de ONTAP, que se describe en esta página.




== Para backups de datos

* Una cuenta en NetApp StorageGRID, AWS S3, Azure Blob o Google Cloud Platform para los destinos de respaldo y los permisos de acceso establecidos.
+
Consulte la https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Lista de permisos de AWS, Azure o S3"^] para obtener más información.

* No es necesario habilitar el servicio de backup y recuperación de BlueXP  en el entorno de trabajo.
+
El servicio de protección frente a ransomware de BlueXP ayuda a configurar un destino de backup mediante la opción Configuración. Consulte link:rp-use-settings.html["Configurar ajustes"].





== Actualice los permisos de usuarios que no son administradores en un entorno de trabajo de ONTAP

Si necesita actualizar los permisos de usuarios que no son administradores para un entorno de trabajo en particular, complete estos pasos.

. Inicie sesión en BlueXP  y busque el entorno de trabajo que necesita sus permisos de usuario de ONTAP actualizados.
. Haga doble clic en el entorno de trabajo para ver los detalles.
. Seleccione *Ver información adicional* para mostrar el nombre de usuario.
. Inicie sesión en la CLI del clúster de ONTAP con el usuario de administrador.
. Mostrar los roles existentes para ese usuario. Introduzca:
+
[listing]
----
security login show -user-or-group-name <username>
----
. Cambiar el rol del usuario. Introduzca:
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. Vuelva a la IU de protección contra ransomware de BlueXP  para aprovecharla.

