---
sidebar: sidebar 
permalink: rp-start-disable.html 
keywords: bluexp, ransomware protection, netapp, disable protection 
summary: Si ya no desea utilizar el servicio de protección frente a ransomware de BlueXP , puede dejar que la licencia caduque. 
---
= Deshabilite la protección frente al ransomware de BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media


[role="lead"]
Si ya no desea utilizar el servicio de protección frente a ransomware de BlueXP , puede dejar que la licencia caduque. También puede deshabilitar políticas que ya no quiera usar.



== Deshabilita el servicio de protección frente a ransomware de BlueXP 

Una vez que la suscripción o la licencia caducan, el servicio desactiva automáticamente las funciones que requieren una suscripción o licencia.

Para obtener más información sobre las acciones que puede seguir realizando después de que caduque la licencia, consulte link:rp-start-licenses.html["Configura las licencias de protección contra ransomware de BlueXP "].



== Deshabilite las políticas de protección

Si desea dejar de usar políticas de protección que se aplican a las cargas de trabajo, puede deshabilitarlas mediante System Manager, llamadas a la API o la CLI.

Puede deshabilitar FPolicy y las políticas de backup en la protección contra ransomware de BlueXP  aplicando una política diferente que no las incluya. Para obtener instrucciones sobre la configuración de políticas de protección, consulte link:rp-use-protect.html["Protege las cargas de trabajo contra ataques de ransomware"].


TIP: Se recomienda no deshabilitar las políticas de instantáneas.
