---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: Empieza a usar la protección contra el ransomware de BlueXP verificando la compatibilidad de tu entorno, el acceso a la red, el inicio de sesión y el navegador web. 
---
= Requisitos previos de protección contra ransomware de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Comience a usar la protección frente al ransomware de BlueXP verificando la preparación de su entorno operativo, inicio de sesión, acceso a red y navegador web.

Para utilizar la protección contra ransomware de BlueXP, necesitarás estos requisitos previos:

* Una cuenta en NetApp StorageGRID o AWS S3 para los destinos de backup y los permisos de acceso establecidos
+
Consulte la https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Lista de permisos de AWS"^] para obtener más detalles.

* ONTAP 9.11.1 y versiones posteriores
+
** Permisos de la ONTAP del administrador de clústeres
** Una licencia de la protección autónoma frente a ransomware de NetApp, utilizada por la protección frente a ransomware de BlueXP, habilitada en la instancia de ONTAP en las instalaciones, según la versión de ONTAP que esté utilizando. Consulte https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Información general sobre la protección de ransomware autónoma"^].
+

NOTE: La versión general de la protección contra ransomware de BlueXP, a diferencia de la versión Preview, incluye una licencia de la tecnología autónoma de protección frente a ransomware de NetApp. Consulte https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Información general sobre la protección de ransomware autónoma"^] para obtener más detalles.

+
Para obtener más información sobre las licencias, consulte link:concept-ransomware-protection.html["Obtén más información sobre la protección frente al ransomware de BlueXP"].



* En BlueXP:
+
** Un entorno de trabajo de BlueXP con almacenamiento en las instalaciones de NetApp (mediante protocolos NAS o CIFS)
** Debe configurarse un conector BlueXP por cada cloud privado virtual (VPC) o en una región en las instalaciones en BlueXP. Consulte https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Documentación de BlueXP para configurar el Connector"^].
+

NOTE: Si tienes varios BlueXP Connectors, el servicio analizará los datos en todos los conectores más allá de los que se muestren actualmente en la interfaz de usuario de BlueXP.

** Una cuenta de BlueXP con al menos un conector activo que se conecta a clústeres de ONTAP en las instalaciones. Todos los entornos de trabajo y origen deben estar en la misma cuenta de BlueXP.
** Una cuenta de usuario de BlueXP con privilegios de administrador de cuenta para detectar recursos
** Un entorno de trabajo de BlueXP con almacenamiento en las instalaciones de NetApp (mediante protocolos NAS o CIFS)
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos estándar de BlueXP"^]





NOTE: El servicio de backup y recuperación de BlueXP ya no tiene que estar habilitado en el entorno de trabajo. El servicio de protección frente a ransomware de BlueXP ayuda a configurar un destino de backup mediante la opción Configuración. Consulte link:rp-use-settings.html["Configurar ajustes"].
