---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: Para utilizar la protección contra ransomware de BlueXP, sigue algunos pasos para configurarla. 
---
= Configura la protección contra el ransomware de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Para utilizar la protección contra ransomware de BlueXP, sigue algunos pasos para configurarla.

Antes de comenzar, revise link:rp-start-prerequisites.html["requisitos previos"] garantizar que su entorno está listo.



== Preparar el destino de la copia de seguridad

Prepare uno de los siguientes destinos de copia de seguridad:

* StorageGRID de NetApp
* Amazon Web Services
* Google Cloud Platform
* Microsoft Azure


Después de configurar las opciones en el destino de backup, lo configurarás más adelante como destino de backup en el servicio de protección contra ransomware de BlueXP. Para obtener más información sobre cómo configurar el destino de los backups en la protección contra ransomware de BlueXP , consulte link:rp-use-settings.html["Configurar destinos de copia de seguridad"].



=== Preparar StorageGRID para que se convierta en destino de backup

Si desea usar StorageGRID como destino de backup, consulte https://docs.netapp.com/us-en/storagegrid-117/index.html["Documentación de StorageGRID"^] Para obtener más detalles acerca de StorageGRID.



=== Prepare AWS para que se convierta en destino de backup

* Configura una cuenta en AWS.
* Configurar https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Permisos de AWS"^] En AWS.


Para obtener más información sobre la gestión de su almacenamiento de AWS en BlueXP, consulte https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Gestione sus bloques de Amazon S3"^].



=== Prepare Azure para que se convierta en destino de backup

* Configura una cuenta en Azure.
* Configurar https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Permisos de Azure"^] En Azure.


Para obtener más información sobre la gestión de su almacenamiento Azure en BlueXP, consulte https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["Gestione sus cuentas de almacenamiento de Azure"^].



== Configure BlueXP

El siguiente paso es configurar BlueXP y el servicio de protección contra ransomware de BlueXP.

Revisión https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["Requisitos de BlueXP para el modo estándar"^].



=== Crear un conector en BlueXP

Debe ponerse en contacto con su representante de ventas de NetApp para probar o utilizar este servicio. Una vez que uses BlueXP Connector, incluirá las funcionalidades adecuadas para el servicio de protección frente a ransomware.

Para crear un conector en BlueXP antes de usar el servicio, comuníquese con el administrador de su organización BlueXP que tenga permisos para crear conectores y consulte la documentación de BlueXP que describe  https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Cómo crear un conector BlueXP"^] .


NOTE: Si tienes varios BlueXP Connectors, el servicio analizará los datos en todos los conectores más allá de los que se muestren actualmente en la interfaz de usuario de BlueXP. Este servicio detecta todos los proyectos y todos los conectores asociados a esta organización.
