---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, 
summary: Para utilizar la protección contra ransomware de BlueXP, sigue algunos pasos para configurarla. 
---
= Configura la protección contra el ransomware de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: /media/


[role="lead"]
Para utilizar la protección contra ransomware de BlueXP, sigue algunos pasos para configurarla.

Antes de comenzar, revise link:rp-start-prerequisites.html["requisitos previos"] garantizar que su entorno está listo.



== Preparar el destino de la copia de seguridad

Prepare uno de los siguientes destinos de copia de seguridad:

* StorageGRID de NetApp
* Amazon Web Services


Después de configurar las opciones en el destino de backup, lo configurarás más adelante como destino de backup en el servicio de protección contra ransomware de BlueXP.



=== Preparar StorageGRID para que se convierta en destino de backup

Si desea usar StorageGRID como destino de backup, consulte https://docs.netapp.com/us-en/storagegrid-117/index.html["Documentación de StorageGRID"^] Para obtener más detalles acerca de StorageGRID.



=== Prepare AWS para que se convierta en destino de backup

* Configura una cuenta en AWS.
* Configurar https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Permisos de AWS"^] En AWS.


Para obtener más información sobre la gestión de su almacenamiento de AWS en BlueXP, consulte https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Gestione sus bloques de Amazon S3"^].



== Configure BlueXP

El siguiente paso es configurar BlueXP y el servicio de protección contra ransomware de BlueXP.

Revisar https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos estándar de BlueXP"^].



=== Crear un conector en BlueXP

Debe ponerse en contacto con su representante de ventas de NetApp para probar este servicio. Una vez que uses BlueXP Connector, incluirá las funcionalidades adecuadas para el servicio de protección frente a ransomware.

Para crear un conector en BlueXP antes de utilizar el servicio, consulte la documentación de BlueXP que se describe https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Cómo crear un conector BlueXP"^].


NOTE: Si tienes varios BlueXP Connectors, el servicio analizará los datos en todos los conectores más allá de los que se muestren actualmente en la interfaz de usuario de BlueXP. Este servicio detecta todos los espacios de trabajo y todos los conectores asociados a esta cuenta.



=== Accede a la protección frente al ransomware de BlueXP

Utilizarás NetApp BlueXP para iniciar sesión en el servicio de protección contra ransomware de BlueXP. En la navegación izquierda de BlueXP, selecciona *Protección* > *Protección contra ransomware*.

Para obtener más información, consulte link:rp-start-login.html["Accede a la protección frente al ransomware de BlueXP"].



=== Configura los destinos de backup en la protección frente al ransomware de BlueXP

Utiliza la opción de destinos de backup de protección contra ransomware de BlueXP para configurar destinos de backup. Para obtener más información, consulte link:rp-use-settings.html["Configure las opciones de configuración"].
