= Soporte de carga de trabajo SAN
:allow-uri-read: 




=== Soporte de carga de trabajo SAN

Esta versión incluye compatibilidad con cargas de trabajo SAN en la BlueXP ransomware protection. Ahora puede proteger cargas de trabajo SAN, además de cargas de trabajo NFS y CIFS.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["Requisitos previos de protección contra ransomware de BlueXP"].



=== Protección mejorada de la carga de trabajo

Esta versión incluye un flujo de trabajo mejorado para proteger cargas de trabajo con o sin protección de datos. Si utiliza otras herramientas de protección de datos de NetApp , como SnapCenter o BlueXP backup and recovery , para sus snapshots o backups, la BlueXP ransomware protection las detecta y le permite mantener las políticas que las rigen. Con esta versión, puede sustituir dichas políticas por las de BlueXP ransomware protection o seguir utilizando las existentes.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["Proteja las cargas de trabajo"] .



=== Notificaciones por correo electrónico

Si la BlueXP ransomware protection detecta un posible ataque, se mostrará una notificación en las Notificaciones de BlueXP y se enviará un correo electrónico a la dirección configurada. El servicio también generará una instantánea inmediatamente.

En este punto, debe ver el correo electrónico, que enumera la gravedad y los recursos afectados y observar el riesgo potencial en la pestaña *Alertas* de BlueXP ransomware protection .

Si configuró una gestión de eventos y seguridad (SIEM) en la BlueXP ransomware protection, el servicio envía detalles de alerta a su sistema SIEM.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Gestionar alertas de ransomware detectadas"] .
