= Compatibilidad con Amazon FSX para ONTAP de NetApp
:allow-uri-read: 




=== Compatibilidad con Amazon FSX para ONTAP de NetApp

Esta versión es compatible con Amazon FSx para NetApp ONTAP. Esta función te ayuda a proteger las cargas de trabajo de FSx para ONTAP con la protección frente a ransomware de BlueXP .

FSX para ONTAP es un servicio totalmente gestionado que proporciona la potencia del almacenamiento de NetApp ONTAP en la nube. Ofrece las mismas funciones, rendimiento y funcionalidades administrativas que utiliza en las instalaciones con la agilidad y la escalabilidad de un servicio nativo de AWS.

Se han realizado los siguientes cambios en el flujo de trabajo de protección frente a ransomware de BlueXP :

* La detección incluye cargas de trabajo en FSx para entornos de trabajo de ONTAP 9,15.
* La pestaña Protección muestra las cargas de trabajo en FSx para entornos ONTAP. En este entorno, debes ejecutar operaciones de backup mediante el servicio de backup de FSx para ONTAP. Puede restaurar estas cargas de trabajo mediante snapshots de protección frente al ransomware de BlueXP .
+

TIP: Las políticas de backup para una carga de trabajo que se ejecuta en FSx para ONTAP no se pueden establecer en BlueXP . Las políticas de backup existentes establecidas en Amazon FSx para NetApp ONTAP no cambian.

* Los incidentes de alertas muestran el nuevo entorno de trabajo de FSx para ONTAP.


Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["Obtén más información sobre los entornos de trabajo y la protección frente al ransomware de BlueXP "] .

Para obtener más información sobre las opciones admitidas, consulte la https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["Limitaciones de protección contra ransomware de BlueXP "].
