= Informes de entornos de trabajo no compatibles en la protección frente al ransomware de BlueXP 
:allow-uri-read: 




=== Informes de entornos de trabajo no compatibles en la protección frente al ransomware de BlueXP 

Durante el flujo de trabajo de detección, la protección frente al ransomware de BlueXP  informa de más detalles al pasar el ratón por cargas de trabajo compatibles o incompatibles. Esto te ayudará a comprender por qué el servicio de protección frente a ransomware de BlueXP  no se detectan algunas de tus cargas de trabajo.

Hay muchas razones por las que el servicio no soporta un entorno de trabajo, por ejemplo, la versión de ONTAP en su entorno de trabajo podría estar por debajo de la versión requerida. Cuando pasa el ratón sobre un entorno de trabajo no admitido, una información sobre herramientas muestra el motivo.

Es posible ver los entornos de trabajo no compatibles durante la detección inicial, donde también se pueden descargar los resultados. También puede ver los resultados de la detección desde la opción *Detección de carga de trabajo* en la página Configuración.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Detecta cargas de trabajo en la protección frente al ransomware de BlueXP"] .
