= Soporte de carga de trabajo SAN
:allow-uri-read: 




=== Soporte de carga de trabajo SAN

Esta versión incluye compatibilidad con cargas de trabajo SAN en la BlueXP ransomware protection. Ahora puede proteger cargas de trabajo SAN, además de cargas de trabajo NFS y CIFS.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["Requisitos previos de protección contra ransomware de BlueXP"].



=== Protección mejorada de la carga de trabajo

Esta versión mejora el proceso de configuración de cargas de trabajo con políticas de snapshots y backup de otras herramientas de NetApp , como SnapCenter o BlueXP backup and recovery. En versiones anteriores, la BlueXP ransomware protection detectaba las políticas de otras herramientas, lo que solo permitía cambiar la política de detección. Con esta versión, ahora puede reemplazar las políticas de snapshots y backup con las políticas de BlueXP ransomware protection o seguir usando las políticas de otras herramientas.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["Proteja las cargas de trabajo"].



=== Notificaciones por correo electrónico

Si la BlueXP ransomware protection detecta un posible ataque, aparece una notificación en Notificaciones de BlueXP y se envía un correo electrónico a la dirección de correo electrónico que usted configuró.

El correo electrónico incluye información sobre la gravedad, la carga de trabajo afectada y un enlace a la alerta en la pestaña *Alertas* de BlueXP ransomware protection .

Si configuró un sistema de gestión de eventos y seguridad (SIEM) en la BlueXP ransomware protection, el servicio envía detalles de alerta a su sistema SIEM.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Gestionar alertas de ransomware detectadas"].
